# Generated by Django 6.0.1 on 2026-01-29 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geom_json', models.TextField(blank=True, null=True, verbose_name='Géométrie (JSON)')),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geom_json', models.TextField(blank=True, null=True, verbose_name='Géométrie (JSON)')),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geom_json', models.TextField(blank=True, null=True, verbose_name='Géométrie (JSON)')),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrondissements', to='geoprod_cm.departement')),
            ],
            options={
                'verbose_name': 'Arrondissement',
                'verbose_name_plural': 'Arrondissements',
                'ordering': ['nom'],
                'unique_together': {('nom', 'departement')},
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='geoprod_cm.region'),
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secteur', models.CharField(choices=[('agriculture', 'Agriculture'), ('elevage', 'Élevage'), ('peche', 'Pêche')], max_length=20)),
                ('produit', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('niveau_administratif', models.CharField(choices=[('region', 'Région'), ('departement', 'Département'), ('arrondissement', 'Arrondissement')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unite', models.CharField(max_length=20)),
                ('source_donnee', models.CharField(max_length=200)),
                ('date_collecte', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrondissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='geoprod_cm.arrondissement')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='geoprod_cm.departement')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='geoprod_cm.region')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'ordering': ['-annee', 'secteur', 'produit'],
                'indexes': [models.Index(fields=['secteur'], name='geoprod_cm__secteur_25892c_idx'), models.Index(fields=['produit'], name='geoprod_cm__produit_6f1f80_idx'), models.Index(fields=['annee'], name='geoprod_cm__annee_67cb5e_idx'), models.Index(fields=['niveau_administratif'], name='geoprod_cm__niveau__468966_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('nom', 'region')},
        ),
    ]
