# Generated by Django 6.0.1 on 2026-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoprod_cm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrondissement',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='departement',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
